{{-- GENERATED by resources/map-data/build_coffee_sketch.py. Do not edit by hand. --}}
<svg class="cof-sketch" id="cofSketch" viewBox="0 0 500 900" preserveAspectRatio="xMidYMid meet" aria-hidden="true" focusable="false">
<defs><filter id="skRough" x="-5%" y="-5%" width="110%" height="110%"><feTurbulence type="fractalNoise" baseFrequency=".035" numOctaves="2" seed="4"/><feDisplacementMap in="SourceGraphic" scale="2.6"/></filter></defs>
<g filter="url(#skRough)">
<path class="sk sk--bold" pathLength="1" d="M-6.0,52.0 C80.0,58.0 150.0,98.0 232.0,124.0 C314.0,150.0 392.0,168.0 468.0,222.0" data-at="0.000" data-to="0.160"/>
<path class="sk" pathLength="1" d="M2,58 C84,64 152,104 230,130 C312,156 388,176 452,222" data-at="0.040" data-to="0.180"/>
<path class="sk" pathLength="1" d="M82.0,69.5 C106.8,70.6 133.7,41.2 139.1,16.4 C113.8,20.8 81.2,44.6 82.0,69.5" data-at="0.050" data-to="0.110"/>
<path class="sk" pathLength="1" d="M82.0,69.5 Q111.6,44.0 133.4,21.7" data-at="0.090" data-to="0.150"/>
<path class="sk sk--fine" pathLength="1" d="M99.1,53.5 L113.6,53.1" data-at="0.110" data-to="0.160"/>
<path class="sk sk--fine" pathLength="1" d="M99.1,53.5 L100.6,39.1" data-at="0.110" data-to="0.160"/>
<path class="sk sk--fine" pathLength="1" d="M111.7,41.8 L125.5,40.7" data-at="0.110" data-to="0.160"/>
<path class="sk sk--fine" pathLength="1" d="M111.7,41.8 L113.8,28.1" data-at="0.110" data-to="0.160"/>
<path class="sk sk--fine" pathLength="1" d="M123.1,31.2 L136.3,29.4" data-at="0.110" data-to="0.160"/>
<path class="sk sk--fine" pathLength="1" d="M123.1,31.2 L125.9,18.2" data-at="0.110" data-to="0.160"/>
<path class="sk" pathLength="1" d="M82.0,69.5 C71.8,89.2 86.7,122.5 107.5,136.8 C112.7,112.6 102.1,78.8 82.0,69.5" data-at="0.070" data-to="0.130"/>
<path class="sk" pathLength="1" d="M82.0,69.5 Q93.5,103.6 104.9,130.1" data-at="0.110" data-to="0.170"/>
<path class="sk sk--fine" pathLength="1" d="M89.6,89.7 L85.2,102.1" data-at="0.130" data-to="0.180"/>
<path class="sk sk--fine" pathLength="1" d="M89.6,89.7 L101.2,96.1" data-at="0.130" data-to="0.180"/>
<path class="sk sk--fine" pathLength="1" d="M95.2,104.5 L91.6,116.6" data-at="0.130" data-to="0.180"/>
<path class="sk sk--fine" pathLength="1" d="M95.2,104.5 L106.0,111.2" data-at="0.130" data-to="0.180"/>
<path class="sk sk--fine" pathLength="1" d="M100.3,117.9 L97.4,129.8" data-at="0.130" data-to="0.180"/>
<path class="sk sk--fine" pathLength="1" d="M100.3,117.9 L110.4,124.9" data-at="0.130" data-to="0.180"/>
<path class="sk" pathLength="1" d="M156.0,96.3 C181.6,100.6 207.2,75.2 214.4,49.2 C188.3,52.5 157.1,71.1 156.0,96.3" data-at="0.090" data-to="0.150"/>
<path class="sk" pathLength="1" d="M156.0,96.3 Q186.2,73.9 208.6,53.9" data-at="0.130" data-to="0.190"/>
<path class="sk sk--fine" pathLength="1" d="M173.6,82.2 L187.7,83.0" data-at="0.150" data-to="0.200"/>
<path class="sk sk--fine" pathLength="1" d="M173.6,82.2 L175.8,68.2" data-at="0.150" data-to="0.200"/>
<path class="sk sk--fine" pathLength="1" d="M186.4,71.8 L199.9,71.9" data-at="0.150" data-to="0.200"/>
<path class="sk sk--fine" pathLength="1" d="M186.4,71.8 L189.2,58.6" data-at="0.150" data-to="0.200"/>
<path class="sk sk--fine" pathLength="1" d="M198.1,62.4 L211.1,61.8" data-at="0.150" data-to="0.200"/>
<path class="sk sk--fine" pathLength="1" d="M198.1,62.4 L201.4,49.8" data-at="0.150" data-to="0.200"/>
<path class="sk" pathLength="1" d="M156.0,96.3 C143.6,116.2 155.8,148.0 174.9,162.7 C181.9,140.4 175.9,105.5 156.0,96.3" data-at="0.110" data-to="0.170"/>
<path class="sk" pathLength="1" d="M156.0,96.3 Q164.2,129.9 173.0,156.1" data-at="0.150" data-to="0.210"/>
<path class="sk sk--fine" pathLength="1" d="M161.7,116.2 L156.1,127.9" data-at="0.170" data-to="0.220"/>
<path class="sk sk--fine" pathLength="1" d="M161.7,116.2 L172.6,123.2" data-at="0.170" data-to="0.220"/>
<path class="sk sk--fine" pathLength="1" d="M165.8,130.8 L161.1,142.2" data-at="0.170" data-to="0.220"/>
<path class="sk sk--fine" pathLength="1" d="M165.8,130.8 L175.9,138.0" data-at="0.170" data-to="0.220"/>
<path class="sk sk--fine" pathLength="1" d="M169.6,144.1 L165.6,155.3" data-at="0.170" data-to="0.220"/>
<path class="sk sk--fine" pathLength="1" d="M169.6,144.1 L178.9,151.5" data-at="0.170" data-to="0.220"/>
<path class="sk sk--fruit" pathLength="1" d="M163.1,106.3 A7.1,7.1 0 1 1 163.1,105.7" data-at="0.150" data-to="0.200"/>
<path class="sk sk--fine" pathLength="1" d="M152.1,104.9 Q152.9,102.1 155.7,101.9" data-at="0.190" data-to="0.220"/>
<circle class="sk-dot" cx="156.8" cy="110.2" r="1.3" data-at="0.200"/>
<path class="sk sk--fruit" pathLength="1" d="M150.4,112.3 A7.3,7.3 0 1 1 150.4,111.7" data-at="0.162" data-to="0.212"/>
<path class="sk sk--fine" pathLength="1" d="M139.0,110.8 Q139.8,107.9 142.7,107.8" data-at="0.202" data-to="0.232"/>
<circle class="sk-dot" cx="143.8" cy="116.3" r="1.3" data-at="0.212"/>
<path class="sk sk--fruit" pathLength="1" d="M176.1,113.3 A8.1,8.1 0 1 1 176.1,112.7" data-at="0.174" data-to="0.224"/>
<path class="sk sk--fine" pathLength="1" d="M163.6,111.7 Q164.4,108.5 167.6,108.3" data-at="0.214" data-to="0.244"/>
<circle class="sk-dot" cx="168.9" cy="117.8" r="1.3" data-at="0.224"/>
<path class="sk" pathLength="1" d="M232.0,124.0 C256.1,126.5 280.5,99.9 285.0,75.3 C260.4,79.5 232.0,99.4 232.0,124.0" data-at="0.130" data-to="0.190"/>
<path class="sk" pathLength="1" d="M232.0,124.0 Q259.5,100.8 279.7,80.2" data-at="0.170" data-to="0.230"/>
<path class="sk sk--fine" pathLength="1" d="M247.9,109.4 L261.8,109.6" data-at="0.190" data-to="0.240"/>
<path class="sk sk--fine" pathLength="1" d="M247.9,109.4 L248.9,95.6" data-at="0.190" data-to="0.240"/>
<path class="sk sk--fine" pathLength="1" d="M259.6,98.7 L272.8,98.2" data-at="0.190" data-to="0.240"/>
<path class="sk sk--fine" pathLength="1" d="M259.6,98.7 L261.2,85.6" data-at="0.190" data-to="0.240"/>
<path class="sk sk--fine" pathLength="1" d="M270.2,88.9 L282.8,87.8" data-at="0.190" data-to="0.240"/>
<path class="sk sk--fine" pathLength="1" d="M270.2,88.9 L272.4,76.5" data-at="0.190" data-to="0.240"/>
<path class="sk" pathLength="1" d="M232.0,124.0 C219.4,143.1 231.2,172.9 248.3,188.0 C256.9,166.1 251.1,134.7 232.0,124.0" data-at="0.150" data-to="0.210"/>
<path class="sk" pathLength="1" d="M232.0,124.0 Q238.8,156.3 246.6,181.6" data-at="0.190" data-to="0.250"/>
<path class="sk sk--fine" pathLength="1" d="M236.9,143.2 L230.9,154.3" data-at="0.210" data-to="0.260"/>
<path class="sk sk--fine" pathLength="1" d="M236.9,143.2 L247.4,150.0" data-at="0.210" data-to="0.260"/>
<path class="sk sk--fine" pathLength="1" d="M240.5,157.3 L235.3,168.1" data-at="0.210" data-to="0.260"/>
<path class="sk sk--fine" pathLength="1" d="M240.5,157.3 L250.2,164.3" data-at="0.210" data-to="0.260"/>
<path class="sk sk--fine" pathLength="1" d="M243.7,170.1 L239.3,180.7" data-at="0.210" data-to="0.260"/>
<path class="sk sk--fine" pathLength="1" d="M243.7,170.1 L252.7,177.3" data-at="0.210" data-to="0.260"/>
<path class="sk sk--fruit" pathLength="1" d="M239.2,134.0 A7.2,7.2 0 1 1 239.2,133.4" data-at="0.190" data-to="0.240"/>
<path class="sk sk--fine" pathLength="1" d="M228.0,132.6 Q228.7,129.7 231.6,129.5" data-at="0.230" data-to="0.260"/>
<circle class="sk-dot" cx="232.7" cy="138.0" r="1.3" data-at="0.240"/>
<path class="sk sk--fruit" pathLength="1" d="M226.8,140.0 A7.8,7.8 0 1 1 226.8,139.4" data-at="0.202" data-to="0.252"/>
<path class="sk sk--fine" pathLength="1" d="M214.7,138.4 Q215.5,135.3 218.6,135.2" data-at="0.242" data-to="0.272"/>
<circle class="sk-dot" cx="219.8" cy="144.3" r="1.3" data-at="0.252"/>
<path class="sk sk--fruit" pathLength="1" d="M251.1,141.0 A7.1,7.1 0 1 1 251.1,140.4" data-at="0.214" data-to="0.264"/>
<path class="sk sk--fine" pathLength="1" d="M240.1,139.6 Q240.8,136.8 243.6,136.6" data-at="0.254" data-to="0.284"/>
<circle class="sk-dot" cx="244.7" cy="144.9" r="1.3" data-at="0.264"/>
<path class="sk sk--fruit" pathLength="1" d="M238.1,149.0 A8.1,8.1 0 1 1 238.1,148.4" data-at="0.226" data-to="0.276"/>
<path class="sk sk--fine" pathLength="1" d="M225.6,147.4 Q226.4,144.2 229.6,144.0" data-at="0.266" data-to="0.296"/>
<circle class="sk-dot" cx="230.8" cy="153.4" r="1.3" data-at="0.276"/>
<path class="sk" pathLength="1" d="M309.6,147.9 C333.9,151.6 357.2,125.0 360.4,101.3 C337.3,104.4 308.8,124.3 309.6,147.9" data-at="0.170" data-to="0.230"/>
<path class="sk" pathLength="1" d="M309.6,147.9 Q336.0,125.8 355.4,106.0" data-at="0.210" data-to="0.270"/>
<path class="sk sk--fine" pathLength="1" d="M324.8,134.0 L338.4,134.4" data-at="0.230" data-to="0.280"/>
<path class="sk sk--fine" pathLength="1" d="M324.8,134.0 L325.5,120.4" data-at="0.230" data-to="0.280"/>
<path class="sk sk--fine" pathLength="1" d="M336.0,123.7 L348.9,123.5" data-at="0.230" data-to="0.280"/>
<path class="sk sk--fine" pathLength="1" d="M336.0,123.7 L337.4,110.9" data-at="0.230" data-to="0.280"/>
<path class="sk sk--fine" pathLength="1" d="M346.2,114.4 L358.5,113.5" data-at="0.230" data-to="0.280"/>
<path class="sk sk--fine" pathLength="1" d="M346.2,114.4 L348.1,102.2" data-at="0.230" data-to="0.280"/>
<path class="sk" pathLength="1" d="M309.6,147.9 C296.9,164.7 305.5,194.0 321.7,209.8 C331.0,190.4 329.3,159.2 309.6,147.9" data-at="0.190" data-to="0.250"/>
<path class="sk" pathLength="1" d="M309.6,147.9 Q314.3,179.1 320.5,203.6" data-at="0.230" data-to="0.290"/>
<path class="sk sk--fine" pathLength="1" d="M313.2,166.5 L306.5,176.8" data-at="0.250" data-to="0.300"/>
<path class="sk sk--fine" pathLength="1" d="M313.2,166.5 L323.3,173.5" data-at="0.250" data-to="0.300"/>
<path class="sk sk--fine" pathLength="1" d="M315.9,180.1 L310.0,190.2" data-at="0.250" data-to="0.300"/>
<path class="sk sk--fine" pathLength="1" d="M315.9,180.1 L325.1,187.3" data-at="0.250" data-to="0.300"/>
<path class="sk sk--fine" pathLength="1" d="M318.3,192.5 L313.2,202.4" data-at="0.250" data-to="0.300"/>
<path class="sk sk--fine" pathLength="1" d="M318.3,192.5 L326.8,199.8" data-at="0.250" data-to="0.300"/>
<path class="sk sk--fruit" pathLength="1" d="M317.0,157.9 A7.5,7.5 0 1 1 317.0,157.3" data-at="0.230" data-to="0.280"/>
<path class="sk sk--fine" pathLength="1" d="M305.5,156.5 Q306.2,153.5 309.2,153.3" data-at="0.270" data-to="0.300"/>
<circle class="sk-dot" cx="310.3" cy="162.0" r="1.3" data-at="0.280"/>
<path class="sk sk--fruit" pathLength="1" d="M304.2,163.9 A7.6,7.6 0 1 1 304.2,163.3" data-at="0.242" data-to="0.292"/>
<path class="sk sk--fine" pathLength="1" d="M292.4,162.4 Q293.1,159.4 296.2,159.2" data-at="0.282" data-to="0.312"/>
<circle class="sk-dot" cx="297.3" cy="168.1" r="1.3" data-at="0.292"/>
<path class="sk sk--fruit" pathLength="1" d="M329.6,164.9 A8.1,8.1 0 1 1 329.6,164.3" data-at="0.254" data-to="0.304"/>
<path class="sk sk--fine" pathLength="1" d="M317.1,163.3 Q317.9,160.1 321.2,159.9" data-at="0.294" data-to="0.324"/>
<circle class="sk-dot" cx="322.4" cy="169.4" r="1.3" data-at="0.304"/>
<path class="sk" pathLength="1" d="M385.0,175.6 C406.7,181.8 431.3,158.4 438.0,136.2 C413.9,136.8 385.1,151.9 385.0,175.6" data-at="0.200" data-to="0.260"/>
<path class="sk" pathLength="1" d="M385.0,175.6 Q412.4,157.1 432.7,140.2" data-at="0.240" data-to="0.300"/>
<path class="sk sk--fine" pathLength="1" d="M400.9,163.8 L414.0,165.9" data-at="0.260" data-to="0.310"/>
<path class="sk sk--fine" pathLength="1" d="M400.9,163.8 L402.7,150.7" data-at="0.260" data-to="0.310"/>
<path class="sk sk--fine" pathLength="1" d="M412.6,155.1 L425.1,156.5" data-at="0.260" data-to="0.310"/>
<path class="sk sk--fine" pathLength="1" d="M412.6,155.1 L414.9,142.8" data-at="0.260" data-to="0.310"/>
<path class="sk sk--fine" pathLength="1" d="M423.2,147.3 L435.2,147.9" data-at="0.260" data-to="0.310"/>
<path class="sk sk--fine" pathLength="1" d="M423.2,147.3 L426.0,135.6" data-at="0.260" data-to="0.310"/>
<path class="sk" pathLength="1" d="M385.0,175.6 C371.9,190.6 379.5,220.7 395.9,234.6 C406.0,216.6 404.2,185.1 385.0,175.6" data-at="0.220" data-to="0.280"/>
<path class="sk" pathLength="1" d="M385.0,175.6 Q389.2,205.4 394.8,228.7" data-at="0.260" data-to="0.320"/>
<path class="sk sk--fine" pathLength="1" d="M388.3,193.3 L381.4,203.1" data-at="0.280" data-to="0.330"/>
<path class="sk sk--fine" pathLength="1" d="M388.3,193.3 L398.3,200.0" data-at="0.280" data-to="0.330"/>
<path class="sk sk--fine" pathLength="1" d="M390.7,206.3 L384.7,216.0" data-at="0.280" data-to="0.330"/>
<path class="sk sk--fine" pathLength="1" d="M390.7,206.3 L399.8,213.2" data-at="0.280" data-to="0.330"/>
<path class="sk sk--fine" pathLength="1" d="M392.9,218.1 L387.6,227.6" data-at="0.280" data-to="0.330"/>
<path class="sk sk--fine" pathLength="1" d="M392.9,218.1 L401.2,225.1" data-at="0.280" data-to="0.330"/>
<path class="sk sk--fruit" pathLength="1" d="M392.7,185.6 A7.7,7.7 0 1 1 392.7,185.0" data-at="0.260" data-to="0.310"/>
<path class="sk sk--fine" pathLength="1" d="M380.8,184.1 Q381.6,181.0 384.7,180.9" data-at="0.300" data-to="0.330"/>
<circle class="sk-dot" cx="385.8" cy="189.8" r="1.3" data-at="0.310"/>
<path class="sk sk--fruit" pathLength="1" d="M379.6,191.6 A7.6,7.6 0 1 1 379.6,191.0" data-at="0.272" data-to="0.322"/>
<path class="sk sk--fine" pathLength="1" d="M367.9,190.1 Q368.6,187.1 371.7,186.9" data-at="0.312" data-to="0.342"/>
<circle class="sk-dot" cx="372.8" cy="195.8" r="1.3" data-at="0.322"/>
<path class="sk sk--fruit" pathLength="1" d="M405.5,192.6 A8.4,8.4 0 1 1 405.5,192.0" data-at="0.284" data-to="0.334"/>
<path class="sk sk--fine" pathLength="1" d="M392.4,190.9 Q393.3,187.6 396.6,187.4" data-at="0.324" data-to="0.354"/>
<circle class="sk-dot" cx="397.9" cy="197.3" r="1.3" data-at="0.334"/>
<path class="sk sk--fruit" pathLength="1" d="M391.6,200.6 A8.5,8.5 0 1 1 391.6,200.0" data-at="0.296" data-to="0.346"/>
<path class="sk sk--fine" pathLength="1" d="M378.4,198.9 Q379.2,195.5 382.6,195.3" data-at="0.336" data-to="0.366"/>
<circle class="sk-dot" cx="383.9" cy="205.3" r="1.3" data-at="0.346"/>
<path class="sk" pathLength="1" d="M445.1,206.8 C465.3,215.8 491.5,197.8 500.5,176.8 C478.4,173.3 448.2,183.2 445.1,206.8" data-at="0.230" data-to="0.290"/>
<path class="sk" pathLength="1" d="M445.1,206.8 Q473.6,193.2 495.0,179.8" data-at="0.270" data-to="0.330"/>
<path class="sk sk--fine" pathLength="1" d="M461.8,197.8 L474.0,202.0" data-at="0.290" data-to="0.340"/>
<path class="sk sk--fine" pathLength="1" d="M461.8,197.8 L465.0,185.3" data-at="0.290" data-to="0.340"/>
<path class="sk sk--fine" pathLength="1" d="M473.9,191.2 L485.8,194.6" data-at="0.290" data-to="0.340"/>
<path class="sk sk--fine" pathLength="1" d="M473.9,191.2 L477.6,179.5" data-at="0.290" data-to="0.340"/>
<path class="sk sk--fine" pathLength="1" d="M485.0,185.2 L496.4,187.8" data-at="0.290" data-to="0.340"/>
<path class="sk sk--fine" pathLength="1" d="M485.0,185.2 L489.1,174.3" data-at="0.290" data-to="0.340"/>
<path class="sk" pathLength="1" d="M445.1,206.8 C428.5,220.1 434.1,248.8 447.0,263.8 C459.0,247.7 462.2,217.8 445.1,206.8" data-at="0.250" data-to="0.310"/>
<path class="sk" pathLength="1" d="M445.1,206.8 Q444.7,235.4 446.8,258.1" data-at="0.290" data-to="0.350"/>
<path class="sk sk--fine" pathLength="1" d="M445.7,223.9 L437.4,232.2" data-at="0.310" data-to="0.360"/>
<path class="sk sk--fine" pathLength="1" d="M445.7,223.9 L454.5,231.6" data-at="0.310" data-to="0.360"/>
<path class="sk sk--fine" pathLength="1" d="M446.1,236.5 L438.7,244.7" data-at="0.310" data-to="0.360"/>
<path class="sk sk--fine" pathLength="1" d="M446.1,236.5 L454.1,244.2" data-at="0.310" data-to="0.360"/>
<path class="sk sk--fine" pathLength="1" d="M446.5,247.9 L439.9,256.1" data-at="0.310" data-to="0.360"/>
<path class="sk sk--fine" pathLength="1" d="M446.5,247.9 L453.7,255.6" data-at="0.310" data-to="0.360"/>
<path class="sk sk--fruit" pathLength="1" d="M453.6,216.8 A8.4,8.4 0 1 1 453.6,216.2" data-at="0.290" data-to="0.340"/>
<path class="sk sk--fine" pathLength="1" d="M440.5,215.1 Q441.3,211.8 444.7,211.6" data-at="0.330" data-to="0.360"/>
<circle class="sk-dot" cx="446.0" cy="221.5" r="1.3" data-at="0.340"/>
<path class="sk sk--fruit" pathLength="1" d="M440.4,222.8 A8.2,8.2 0 1 1 440.4,222.2" data-at="0.302" data-to="0.352"/>
<path class="sk sk--fine" pathLength="1" d="M427.6,221.2 Q428.4,217.9 431.7,217.7" data-at="0.342" data-to="0.372"/>
<circle class="sk-dot" cx="433.0" cy="227.4" r="1.3" data-at="0.352"/>
<path class="sk sk--fruit" pathLength="1" d="M465.5,223.8 A8.4,8.4 0 1 1 465.5,223.2" data-at="0.314" data-to="0.364"/>
<path class="sk sk--fine" pathLength="1" d="M452.5,222.2 Q453.4,218.8 456.7,218.6" data-at="0.354" data-to="0.384"/>
<circle class="sk-dot" cx="458.0" cy="228.5" r="1.3" data-at="0.364"/>
<mask id="skTrailMask" maskUnits="userSpaceOnUse" x="0" y="0" width="500" height="900"><path class="sk-mask" pathLength="1" d="M462,252 C500,330 432,392 468,468 C502,540 420,610 300,668" data-at=".30" data-to=".66"/></mask><path class="sk-trail" d="M462,252 C500,330 432,392 468,468 C502,540 420,610 300,668" mask="url(#skTrailMask)"/>
<g class="sk-bean" data-at="0.341" transform="translate(471.7 280.6) rotate(36)"><ellipse rx="6.2" ry="8.8"/><path d="M0,-7.6 C-3,-3 3,2 0,7.6"/></g>
<g class="sk-bean" data-at="0.384" transform="translate(471.1 334.6) rotate(-13)"><ellipse rx="6.2" ry="8.8"/><path d="M0,-7.6 C-3,-3 3,2 0,7.6"/></g>
<g class="sk-bean" data-at="0.426" transform="translate(460.3 386.8) rotate(-12)"><ellipse rx="6.2" ry="8.8"/><path d="M0,-7.6 C-3,-3 3,2 0,7.6"/></g>
<g class="sk-bean" data-at="0.469" transform="translate(459.0 440.1) rotate(-48)"><ellipse rx="6.2" ry="8.8"/><path d="M0,-7.6 C-3,-3 3,2 0,7.6"/></g>
<g class="sk-bean" data-at="0.511" transform="translate(475.5 494.9) rotate(16)"><ellipse rx="6.2" ry="8.8"/><path d="M0,-7.6 C-3,-3 3,2 0,7.6"/></g>
<g class="sk-bean" data-at="0.554" transform="translate(461.4 547.6) rotate(-53)"><ellipse rx="6.2" ry="8.8"/><path d="M0,-7.6 C-3,-3 3,2 0,7.6"/></g>
<g class="sk-bean" data-at="0.596" transform="translate(414.9 598.2) rotate(-52)"><ellipse rx="6.2" ry="8.8"/><path d="M0,-7.6 C-3,-3 3,2 0,7.6"/></g>
<g class="sk-bean" data-at="0.639" transform="translate(343.1 645.7) rotate(-35)"><ellipse rx="6.2" ry="8.8"/><path d="M0,-7.6 C-3,-3 3,2 0,7.6"/></g>
<path class="sk" pathLength="1" d="M168,686 C196,664 300,662 338,684" data-at="0.620" data-to="0.720"/>
<path class="sk" pathLength="1" d="M168,686 C204,706 304,706 338,684" data-at="0.640" data-to="0.740"/>
<path class="sk" pathLength="1" d="M166,688 C160,700 162,712 170,720 C214,738 296,738 338,718 C344,710 344,698 338,686" data-at="0.660" data-to="0.760"/>
<path class="sk sk--bold" pathLength="1" d="M171,720 C138,760 130,830 146,872 C150,884 158,890 172,892" data-at="0.700" data-to="0.800"/>
<path class="sk sk--bold" pathLength="1" d="M172,892 C214,900 292,900 330,890" data-at="0.740" data-to="0.840"/>
<path class="sk sk--bold" pathLength="1" d="M330,890 C350,878 356,836 352,800 C348,764 338,738 336,720" data-at="0.760" data-to="0.860"/>
<path class="sk" pathLength="1" d="M164,748 C157,774 156,804 160,830" data-at="0.800" data-to="0.900"/>
<path class="sk" pathLength="1" d="M334,748 C341,776 342,806 338,830" data-at="0.810" data-to="0.910"/>
<path class="sk" pathLength="1" d="M232,738 C230,746 234,754 232,762" data-at="0.820" data-to="0.920"/>
<path class="sk sk--fine" pathLength="1" d="M184,871.6 l6,-3" data-at="0.820" data-to="0.860"/>
<path class="sk sk--fine" pathLength="1" d="M202,873.4 l6,-3" data-at="0.820" data-to="0.860"/>
<path class="sk sk--fine" pathLength="1" d="M220,870.5 l6,-3" data-at="0.820" data-to="0.860"/>
<path class="sk sk--fine" pathLength="1" d="M238,870.0 l6,-3" data-at="0.820" data-to="0.860"/>
<path class="sk sk--fine" pathLength="1" d="M256,871.5 l6,-3" data-at="0.820" data-to="0.860"/>
<path class="sk sk--fine" pathLength="1" d="M274,871.0 l6,-3" data-at="0.820" data-to="0.860"/>
<path class="sk sk--fine" pathLength="1" d="M292,873.6 l6,-3" data-at="0.820" data-to="0.860"/>
<path class="sk sk--fine" pathLength="1" d="M310,870.3 l6,-3" data-at="0.820" data-to="0.860"/>
<path class="sk sk--fine" pathLength="1" d="M328,878.7 l6,-3" data-at="0.820" data-to="0.860"/>
<g class="sk-bean sk-bean--pile" data-at="0.680" transform="translate(226.0 676.0) rotate(-30)"><ellipse rx="6.2" ry="8.8"/><path d="M0,-7.6 C-3,-3 3,2 0,7.6"/></g>
<g class="sk-bean sk-bean--pile" data-at="0.695" transform="translate(250.0 670.0) rotate(20)"><ellipse rx="6.2" ry="8.8"/><path d="M0,-7.6 C-3,-3 3,2 0,7.6"/></g>
<g class="sk-bean sk-bean--pile" data-at="0.710" transform="translate(274.0 677.0) rotate(-10)"><ellipse rx="6.2" ry="8.8"/><path d="M0,-7.6 C-3,-3 3,2 0,7.6"/></g>
<g class="sk-bean sk-bean--pile" data-at="0.725" transform="translate(300.0 672.0) rotate(40)"><ellipse rx="6.2" ry="8.8"/><path d="M0,-7.6 C-3,-3 3,2 0,7.6"/></g>
<g class="sk-bean sk-bean--pile" data-at="0.740" transform="translate(238.0 686.0) rotate(70)"><ellipse rx="6.2" ry="8.8"/><path d="M0,-7.6 C-3,-3 3,2 0,7.6"/></g>
<g class="sk-bean sk-bean--pile" data-at="0.755" transform="translate(288.0 688.0) rotate(-50)"><ellipse rx="6.2" ry="8.8"/><path d="M0,-7.6 C-3,-3 3,2 0,7.6"/></g>
<g class="sk-bean sk-bean--pile" data-at="0.900" transform="translate(372.0 884.0) rotate(60)"><ellipse rx="6.2" ry="8.8"/><path d="M0,-7.6 C-3,-3 3,2 0,7.6"/></g>
<g class="sk-bean sk-bean--pile" data-at="0.920" transform="translate(392.0 890.0) rotate(-20)"><ellipse rx="6.2" ry="8.8"/><path d="M0,-7.6 C-3,-3 3,2 0,7.6"/></g>
<g class="sk-bean sk-bean--pile" data-at="0.940" transform="translate(128.0 888.0) rotate(30)"><ellipse rx="6.2" ry="8.8"/><path d="M0,-7.6 C-3,-3 3,2 0,7.6"/></g>
<g class="sk-type" data-at="0.860"><text x="248" y="790" text-anchor="middle" class="sk-t1">COFFEE</text><text x="248" y="826" text-anchor="middle" class="sk-t1">EXPORT</text><text x="248" y="852" text-anchor="middle" class="sk-t2">PRODUCE OF ETHIOPIA</text></g>
<path class="sk sk--fine" pathLength="1" d="M196,800 L204,802 M292,802 L300,800" data-at="0.880" data-to="0.920"/>
</g>
</svg>
